/**
 * Default courselist definition
 */
#include <lse.h>

//course list on world and special
const uint8_t _lseWorldStageTypes[LSE_DEFAULT_NUM_WORLDS + LSE_DEFAULT_NUM_SPECIALS][LSE_DEFAULT_NUM_STAGES] = {
//1
	{LSE_STAGE_TYPE_PIPE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_MYSTERY_BOX, 
	LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_TOADHOUSE, LSE_STAGE_TYPE_NORMAL},
//2
	{LSE_STAGE_TYPE_PIPE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_MYSTERY_BOX, 
	LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_TOADHOUSE, LSE_STAGE_TYPE_NORMAL},
//3
	{LSE_STAGE_TYPE_PIPE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_TOADHOUSE_ALBUM, 
	LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL},
//4
	{LSE_STAGE_TYPE_PIPE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_MYSTERY_BOX, LSE_STAGE_TYPE_NORMAL, 
	LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL},
//5
	{LSE_STAGE_TYPE_PIPE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, 
	LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_TOADHOUSE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL},
//6
	{LSE_STAGE_TYPE_PIPE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, 
	LSE_STAGE_TYPE_MYSTERY_BOX, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL},
//7
	{LSE_STAGE_TYPE_PIPE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_TOADHOUSE, 
	LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL},
//8-1
	{LSE_STAGE_TYPE_PIPE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, 
	LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_EMPTY, LSE_STAGE_TYPE_NORMAL},
//8-2
	{LSE_STAGE_TYPE_PIPE, LSE_STAGE_TYPE_EMPTY, LSE_STAGE_TYPE_EMPTY, LSE_STAGE_TYPE_NORMAL, 
	LSE_STAGE_TYPE_EMPTY, LSE_STAGE_TYPE_EMPTY, LSE_STAGE_TYPE_EMPTY, LSE_STAGE_TYPE_NORMAL},

//S1
	{LSE_STAGE_TYPE_PIPE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_TOADHOUSE, 
	LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_MYSTERY_BOX, LSE_STAGE_TYPE_NORMAL},
//S2
	{LSE_STAGE_TYPE_PIPE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, 
	LSE_STAGE_TYPE_TOADHOUSE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL},
//S3
	{LSE_STAGE_TYPE_PIPE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, 
	LSE_STAGE_TYPE_MYSTERY_BOX, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL},
//S4
	{LSE_STAGE_TYPE_PIPE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, 
	LSE_STAGE_TYPE_TOADHOUSE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL},
//S5
	{LSE_STAGE_TYPE_PIPE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, 
	LSE_STAGE_TYPE_MYSTERY_BOX, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL},
//S6
	{LSE_STAGE_TYPE_PIPE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, 
	LSE_STAGE_TYPE_TOADHOUSE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL},
//S7
	{LSE_STAGE_TYPE_PIPE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, 
	LSE_STAGE_TYPE_MYSTERY_BOX, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL},
//S8
	{LSE_STAGE_TYPE_CHAMPIONSHIP, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, 
	LSE_STAGE_TYPE_TOADHOUSE, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL, LSE_STAGE_TYPE_NORMAL}
};
